### ISSUE TITLE
my model only detect 10 objects, how can i detect more object

### ISSUE THREAD

**Issue by airuikun** [microsoft/customvision-tfjs#15]
<img width="666" alt="image" src="https://user-images.githubusercontent.com/12043709/164981903-6e4ea05d-b7d7-4c0e-a65b-18141361548f.png">

i want to detect all objects, like image, i have 28 objects,  but now only can detect 10 objects
how can i detect all objects, thank you~ 

my code:
```javascript
import * as cvstfjs from '@microsoft/customvision-tfjs';

let model = new cvstfjs.ObjectDetectionModel();
await model.loadModelAsync('http://127.0.0.1:7160/public/customvision-modal/model.json');

const image = document.getElementById('img');
const predictions = await model.executeAsync(image);
    
```

**Comment by shonohs** [comment]
Hi,

A quick solution is to train the project with "general (compact) [S1]" domain. It has a newer architecture and can detect more than 10 boxes.

**Comment by airuikun** [comment]
> Hi,
> 
> A quick solution is to train the project with "general (compact) [S1]" domain. It has a newer architecture and can detect more than 10 boxes.

thank u very much~!
