### ISSUE TITLE
Should loadModelAsync use tf.loadLayersModel instead of tf.LoadGraphModel()?

### ISSUE THREAD

**Issue by armandov91** [microsoft/customvision-tfjs#3]
I am experiencing a small issued with a model, when getting load I get: Uncaught (in promise) TypeError: Cannot read property 'producer' of undefined

**Comment by shonohs** [comment]
Hello,

Thanks for reporting the issue.

Could you tell us about the environment you used and the repro steps? I couldn't reproduce the issue on my environment.
