### ISSUE TITLE
Doesn't work with new version of Node JS

### ISSUE THREAD

**Issue by shaijut** [microsoft/customvision-tfjs#4]
Nothing works with new version of Node JS.

I fixed few errors to run the code , then finally got `Javascript “Not a Constructor”` in below line:

`let model = new cvstfjs.ObjectDetectionModel();`

Kindly check.

**Comment by shonohs** [comment]
Thank you for the feedback. We are looking into the issue.

**Comment by shaijut** [comment]
Also Kindly Check with New version of `Tensorflow.js`

**Comment by shonohs** [comment]
We've made a new package for Node.js environment.
https://github.com/microsoft/customvision-tfjs-node

This is still in preview and is not published to the NPM repository yet.

Sample scripts will be provided soon.

**Comment by shonohs** [comment]
The package is now officially released.

You can find samples scripts in:
https://github.com/Azure-Samples/customvision-export-samples/tree/main/samples/javascript/tensorflowjs
