### ISSUE TITLE
Option To Load the complete Model 

### ISSUE THREAD

**Issue by shaijut** [microsoft/customvision-tfjs#5]
Currently We are Loading the Model all time to get the results. Using this for every frame of video is not good option.

Provide a option to Load the Model on Page Load. 

Then use the Model to  make real time predictions like Object Tracking in a Video.

**Comment by shonohs** [comment]
You can call executeAsync() method multiple times.

Users can decide when/how to initialize the model in their script. We don't have a plan to provide an option to load the model automatically.
