### ISSUE TITLE
Custom Vision TFJS Models are now incompatible and throw errors

### ISSUE THREAD

**Issue by bknutson77** [microsoft/customvision-tfjs#6]
Literally everything is broken.. try it out, the tfjs models being exported by custom vision are completely different than what your code is expecting.  Specifically the postprocessing method is trying to index into the model, but the model's structure is different and so it tries to get index 0 of null at some point.

**Comment by shonohs** [comment]
Thanks for the feedback, and sorry for late response. I will take a look at it today.

**Comment by bknutson77** [comment]
> Thanks for the feedback, and sorry for late response. I will take a look at it today.

No worries!  Just thought I'd let you know.  This stuff is constantly changing.. I tried creating a model with Google AutoML and exported that to TFJS, used that in combination with the library of TFJS-AutoML and it worked.  Custom Vision might be exporting a totally different, new idea of the model and it may have changed on ya.

**Comment by shonohs** [comment]
Hi,

I've tried 3 models (Classification, non-S1 Object Detection, S1 Object Detection) with the sample scripts but I couldn't reproduce the issue.
https://github.com/Azure-Samples/customvision-export-samples/tree/main/samples/javascript/tensorflowjs

Could you provide more details about the issue?
- Classification or Object Detection?
- compact domain or compact [S1] domain?
- When was the project trained?
- Any error messages?

**Comment by bknutson77** [comment]
> Hi,
> 
> I've tried 3 models (Classification, non-S1 Object Detection, S1 Object Detection) with the sample scripts but I couldn't reproduce the issue.
> https://github.com/Azure-Samples/customvision-export-samples/tree/main/samples/javascript/tensorflowjs
> 
> Could you provide more details about the issue?
> 
> * Classification or Object Detection?
> * compact domain or compact [S1] domain?
> * When was the project trained?
> * Any error [messages?[](url)]([url]([url]([url](url))))

**Comment by bknutson77** [comment]
I didn't mean to close this..

**Comment by bknutson77** [comment]
> Hi,
> 
> I've tried 3 models (Classification, non-S1 Object Detection, S1 Object Detection) with the sample scripts but I couldn't reproduce the issue.
> https://github.com/Azure-Samples/customvision-export-samples/tree/main/samples/javascript/tensorflowjs
> 
> Could you provide more details about the issue?
> 
> * Classification or Object Detection?
> * compact domain or compact [S1] domain?
> * When was the project trained?
> * Any error messages?

It was a non-S1 Object Detection, trained last week and exported last week, the error message started in the post-processing method.  I have a feeling that it could be something in common with some of the other ML.NET issues where standard sample models like coco or yolo work but other user-exported models don't, I'm trying to see if I can give you my model.

**Comment by bknutson77** [comment]
> Hi,
> 
> I've tried 3 models (Classification, non-S1 Object Detection, S1 Object Detection) with the sample scripts but I couldn't reproduce the issue.
> https://github.com/Azure-Samples/customvision-export-samples/tree/main/samples/javascript/tensorflowjs
> 
> Could you provide more details about the issue?
> 
> * Classification or Object Detection?
> * compact domain or compact [S1] domain?
> * When was the project trained?
> * Any error messages?

Try this object detection model (I just generated this with a quick train today) https://drive.google.com/file/d/1141nDeOomP6AvEVPT1zDRswSA4LFq6h4/view?usp=sharing

You'll get an error on line 48 of index.js, where it tries to call const channels = outputs[0][0][0].length; it will complain that outpus[0][0] is undefined, and thus output[0][0][0] cannot be accessed.

**Comment by bknutson77** [comment]
This is strange.. when I used the code from here: https://github.com/Azure-Samples/customvision-export-samples/tree/main/samples/javascript/tensorflowjs it works, but if I used your repo directly it was giving me the error.. I'm not sure what's going on but I got it to work with the model, cool!
